### ISSUE TITLE
Get random node

### ISSUE THREAD

**Issue by damian0815** [damian0815/drawify#1]
Returns any random node that was created in the last X days. This will be used for the browser, to randomly discover new storylines.

**Comment by onato** [comment]
http://drawify.onato.com/nodes/random/1345841514.json

I does not return nodes that the user created themself.

The old random is now called randomUnresponded again.

**Comment by damian0815** [comment]
1. What does the `1345841514` mean? I mean I know it's a timestamp, but of what, and how is it used?
2. Can I please have something like `nodes/random/1345841514.json?type=d` and `nodes/random/1345841514.json?type=s` to filter to only drawings or only sentences? (Missing type specifier would mean, select from both). Before I had `nodes/random/d.json` and `nodes/random/s.json` which were handy.

**Comment by onato** [comment]
The 1345... is a timestamp filter. No node created earlier is returned. It is now a named parameter to make it more clear.

I have added the type parameter.

http://drawify.onato.com/nodes/random.json?after=1356841514&type=s

**Comment by damian0815** [comment]
ahh, great, thanks!
