### ISSUE TITLE
Create Text / Create Drawing leaves broken nodes in DB

### ISSUE THREAD

**Issue by damian0815** [damian0815/drawify#126]
There's a couple of bad elements in the database, I'm not sure what's going on with them:

http://drawify2.onato.com/nodes/view/322.json
http://drawify2.onato.com/nodes/view/326.json
http://drawify2.onato.com/nodes/view/313.json
http://drawify2.onato.com/nodes/view/341.json
http://drawify2.onato.com/nodes/view/333.json
http://drawify2.onato.com/nodes/view/345.json
http://drawify2.onato.com/nodes/view/347.json

On a bit of investigating, this is happening when you choose 'create text' or 'create drawing' from the main menu (those are options that show up after you have drawified/textified 5 things, or with the next version you'll be able to switch them on/off via the Settings app).

What happened was this: 

346 was the last node, I hit the 'Create text' button, entered some text, hit the tick -- this created invalid node 347 and valid node 348.

Can repeat 100% -- go to the Create text or Create drawing and after saving, you get one invalid and one valid node in the database, whether it's a text or a drawing.

**Comment by onato** [comment]
Fixed. CakePHP was adding a new record when the non-existent parent could not be found.
