### ISSUE TITLE
nodes/random.json has different json format to nodes/view/id.json

### ISSUE THREAD

**Issue by damian0815** [damian0815/drawify#129]
The json returned by random.json should be identical to the json returned by nodes/view/(nodeId).json for the same nodeId. 

To reproduce:
1. fetch a random node > a.txt
2. fetch the same node manually via view/(nodeId).json > b.text
3. diff a.txt b.txt

Expected result: no difference
Actual result: b.txt includes
- parent/children 
- Liker information
- **Has different date format**

Example:
random.json returning node 311:

```
$ curl -b cookies.txt "http://drawify.onato.com/nodes/random.json?type=s&after=1375620832"
{"node":{"Node":{"id":"311","name":" ","data":"A Chinese Raspberry ","type":"s","user_id":"8","parent_node_id":"233","date_created":"2013-08-17 13:30:32",
"date_updated":"2013-08-30 05:42:42","notify":true}}}
```

manual fetch of node 311:

```
$ curl -b cookies.txt "http://drawify.onato.com/nodes/view/311.json"
{"node":{"Node":{"id":"311","name":" ","data":"A Chinese Raspberry ","type":"s","user_id":"8","parent_node_id":"233","date_created":1376746232,
"date_updated":1377841362,"notify":true},"ParentNode":"233","ChildNode":["493"],"Liker":0}}
```

**Comment by onato** [comment]
Are you referring to the date format or the lack of ParentNode, ChildNode and liker?

I have fixed the date format.

**Comment by onato** [comment]
I am now redirecting to the view action. This way there will be no difference in the format. Hopefully your code can handle the redirect.
