### ISSUE TITLE
Invite new facebook users

### ISSUE THREAD

**Issue by damian0815** [damian0815/drawify#20]
ie, users' Facebook friends who don't already have Drawify accounts could receive an invite via Facebook to download + install the app.

ref Facebook hosting policy, would require an https:// landing page on the http://drawifyapp.com homepage

**Comment by onato** [comment]
I guess we would require a certificate too. It would make sense to do this when we move to our own server. I am not sure how long we will keep the Fluid Forms Server.

**Comment by damian0815** [comment]
Done!
