### ISSUE TITLE
User messaging: inbox

### ISSUE THREAD

**Issue by damian0815** [damian0815/drawify#25]
List of messages with receiver==userId

**Comment by damian0815** [comment]
@onato actually I think this should actually not be on the User object, but rather a separate API call -- this would prevent me having to reload the whole user object whenever i want to check for messages.

**Comment by onato** [comment]
http://drawify.onato.com/messages/inbox.json
http://drawify.onato.com/messages/outbox.json
http://drawify.onato.com/messages/add       POST
http://drawify.onato.com/messages/view/[id].json
http://drawify.onato.com/messages/delete/[id].json
