### ISSUE TITLE
User load failing with error

### ISSUE THREAD

**Issue by damian0815** [damian0815/drawify#45]
Getting an error loading a user when logging in with that user via http://drawify.onato.com/users/view/3.json.

Gist is here: https://gist.github.com/damiannz/a0443f1fe97fb7300053

@onato this is blocking further development (I can't login), can you please fix ASAP

**Comment by damian0815** [comment]
So further info. A long time ago I wrote some code that would make another fetch request after fetching the user from users/getByFacebookToken, as the data returned by users/getByFacebookToken is different to the data returned by users/view .

Can you make it so that a getByFacebookToken just issues a redirect to the users/view/[id].json, so that I don't have to do this internally? I think this would also mean one less function to debug, right?

**Comment by damian0815** [comment]
Ok have worked around this so I'm no longer blocked...

**Comment by onato** [comment]
Sorry, forgot to create the message table on the server.

I am now returning the same content from getByFace... and view. Did I understand you right?

**Comment by damian0815** [comment]
yep, seems to be working better now, thanks!
