### ISSUE TITLE
Error calling getFacebookFriends

### ISSUE THREAD

**Issue by damian0815** [damian0815/drawify#46]
gist: https://gist.github.com/damiannz/553cadcd27264201da01

logged in as drawify id 9, fbToken BAAHDQoHYLxwBAPVyjrr8w33bhKvxPpkSU0ZCZCfla7Yi0Oacb4jf3eSrxtcRFxKZAZAhDm506umypHT6FLc7dX7lY4Le7tnFcdSZCa46YagGojlX3BjzZBkGo4Pcy1H1cvJJJKMfi2vyyYWwkFRTWp

**Comment by onato** [comment]
Not sure why but facebook will not give me your friends...

https://graph.facebook.com/me?fields=id,friends&access_token=BAAHDQoHYLxwBAPVyjrr8w33bhKvxPpkSU0ZCZCfla7Yi0Oacb4jf3eSrxtcRFxKZAZAhDm506umypHT6FLc7dX7lY4Le7tnFcdSZCa46YagGojlX3BjzZBkGo4Pcy1H1cvJJJKMfi2vyyYWwkFRTWp

**Comment by onato** [comment]
I fixed the error but it seems that you don't have any friends...

https://graph.facebook.com/me/friends?access_token=BAAHDQoHYLxwBAPVyjrr8w33bhKvxPpkSU0ZCZCfla7Yi0Oacb4jf3eSrxtcRFxKZAZAhDm506umypHT6FLc7dX7lY4Le7tnFcdSZCa46YagGojlX3BjzZBkGo4Pcy1H1cvJJJKMfi2vyyYWwkFRTWp
