### ISSUE TITLE
push notifications not coming through for user 7

### ISSUE THREAD

**Issue by damian0815** [damian0815/drawify#52]
User 3 receives push notifications of things created by user 7, but user 7 doesn't receive notifications back from user 3's creations.

`2013-03-19 21:03:21.880 Drawify[1852:907] Register URL: http://drawify.onato.com/apns/apns.php?task=register&appname=Drawify&appversion=0.4.40&deviceuid=8d90bf60a9b4a4bec793be64f7690a2c0f0fd037&devicetoken=1f4ab87de176ee8985660402269090fba59b99d1af04d9118bfba731b489bade&devicename=iPod%20touch&devicemodel=iPod%20touch&deviceversion=6.0.1&pushbadge=enabled&pushalert=enabled&pushsound=enabled&user_id=7
2013-03-19 21:03:21.884 Drawify[1852:907] Return Data as string:`

**Comment by onato** [comment]
There seems to be a problem with the certificate again. Did you change something?

http://drawify.onato.com/apns/notifyUser.php?user_id=7&node_id=87&isDrawing=0

**Comment by onato** [comment]
Oops, the problem was that the new devices were being created with instructions to use the production PNS server. Should be fine now.
