### ISSUE TITLE
Unix timestamps on create/update dates are off by 60 minutes

### ISSUE THREAD

**Issue by damian0815** [damian0815/drawify#65]
I just created an node (224). time here is 14:11, Google tells me that means 13:11 GMT.

the date_created and date_updated values in the json returned when i fetch http://drawify.onato.com/nodes/view/224.json are: "date_created":1364127098,"date_updated":1364127098

However, http://www.onlineconversion.com/unix_time.htm tells me that 1364127098 is actually Sun, 24 Mar 2013 12:11:38 GMT .

So something is busted...

**Comment by damian0815** [comment]
The update date is also off by the same amount when i `like` a node. I just fetched http://drawify.onato.com/nodes/like/166.json and the returned date_updated is 1364127515, "Sun, 24 Mar 2013 12:18:35 GMT", again 1 hour out.

**Comment by damian0815** [comment]
Unlike exhibits the same error.

**Comment by onato** [comment]
This date is actually intentionally GMT. This enables us to move the server later to a different timezone or have the code running on different servers spread over different time zones. 

Can you adjust for this on your side?

**Comment by damian0815** [comment]
Hmm, I'm confused. I was expecting the date to be a Unix timestamp, ie the number of seconds elapsed since January 1, 1970 00:00:00 GMT. But that's not what's happening. 

I created node 224 at 13:11 GMT on Sunday, March 24. The date_created field on the node is 1364127098. `TZ=GMT date -r 1364127098` gives me `Sun Mar 24 12:11:38 GMT 2013` which is 60 minutes off.

I can't repair this on my end, since I don't know what's going on.

**Comment by damian0815** [comment]
For reference I would expect the date_created field on 224 to be 1364130698. Ref: http://www.epochconverter.com/

**Comment by onato** [comment]
Sorry, I didn't realise that PHP was automatically factoring the timezone in when converting a date to a timestamp. Should be fine now. I changed the date function in the user controller and added a date_created to the message model.
