### ISSUE TITLE
First startup: simplify/tips/how to play

### ISSUE THREAD

**Issue by damian0815** [damian0815/drawify#66]
It's not totally clear to a first-time player what the words 'drawify' and 'textify' mean. Also, re-use of the words 'drawing' and 'text' in the buttons is confusing (3x 'text', 3x 'draw').

Strategies:
1. Hide the create new text/ create new drawing buttons on first startup. Show them after x drawifies/textifies.
2. First-play walkthrough/tooltips.

(thx @danjah for the comments)

**Comment by onato** [comment]
We could show an initial explanation intro like in mailbox or feedly.
