### ISSUE TITLE
Newly created content is assigned to user 1 rather than logged in user

### ISSUE THREAD

**Issue by damian0815** [damian0815/drawify#73]
POST to `http://drawify.onato.com/nodes/add.json`:

`Node[name]=%20&Node[data]=the%20twister%20went%20for%20a%20walk%20having%20laid%20waste%20to%20everything&Node[type]=s&Node[user_id]=4&Node[parent_node_id]=236`

Result: 

`{"node":{"Node":{"id":"237","name":" ","data":"the twister went for a walk having laid waste to everything","type":"s","user_id":"1","parent_node_id":"236","date_created":1364825748,"date_updated":1364825748,"notify":true},"ParentNode":"236","ChildNode":[],"Liker":0}}`

Note `"user_id":"1"` (expected user_id is the currently logged-in user, ignoring the value POSTed).

**Comment by onato** [comment]
oops, fixed
